name: ci

on:
  push:
  pull_request:

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black ruff || true

      - name: Lint (ruff)
        run: ruff .

      - name: Format check (black)
        run: black --check .

      - name: Import smoke tests
        run: |
          python - <<'PY'
          import importlib
          for m in ["etl.common", "etl.bls_ingest", "etl.bls_ces_ingest", "etl.stocks_ingest"]:
              importlib.import_module(m)
          print("Imports OK")
          PY