name: nightly-refresh

on:
  schedule:
    - cron: "0 6 * * *"   # 06:00 UTC daily
  workflow_dispatch:       # allow manual run from Actions tab

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      # Use discrete PG* vars (matches your code)
      PGHOST:     ${{ secrets.PGHOST }}
      PGPORT:     ${{ secrets.PGPORT }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGUSER:     ${{ secrets.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      BLS_API_KEY: ${{ secrets.BLS_API_KEY }}
      BLS_START_YEAR: "2000"
      PYTHONUNBUFFERED: "1"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch BLS headline unemployment
        run: python etl/bls_ingest.py 2000 2100

      - name: Fetch BLS CES supersectors
        run: python etl/bls_ces_ingest.py 2000 2100

      - name: Fetch equities/ETFs
        run: python etl/stocks_ingest.py

      - name: Load all CSVs into Postgres
        run: python etl/load_to_db.py